import * as fs from "node:fs";
import * as path from "node:path";
import {createRequire} from "node:module";
import remarkGfm from "remark-gfm";
import type {StorybookConfig} from "@storybook/react-vite";

/**
 * Extracts Wonder Blocks token values into .storybook/wb-token-values.gen.js
 * so the Storybook manager theme can use them.
 *
 * The manager theme (`create()` from storybook/theming) runs color math on
 * its values, so it needs concrete hexes — but the WB JS exports resolve to
 * "var(--wb-...)" strings, and the per-theme hexes only exist in the
 * package's shipped CSS. This runs on every `storybook dev`/`build` startup,
 * so the values track upgrades of @khanacademy/wonder-blocks-tokens.
 */
function writeWbTokenValues() {
    const tokenVars = ["--wb-semanticColor-core-foreground-instructive-default"];
    const themeSelectors = {
        "default": ":root, [data-wb-theme='default']",
        "thunderblocks": "[data-wb-theme='thunderblocks']",
        "syl-dark": "[data-wb-theme='syl-dark']",
    };

    const require = createRequire(import.meta.url);
    const css = fs.readFileSync(
        require.resolve("@khanacademy/wonder-blocks-tokens/styles.css"),
        "utf8",
    );

    const values: Record<string, Record<string, string>> = {};
    // The tokens CSS is flat (no nested rules), so a simple block walk works.
    for (const [, selector, body] of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
        const theme = Object.entries(themeSelectors).find(
            ([, sel]) => selector.trim() === sel,
        )?.[0];
        if (!theme) {
            continue;
        }
        for (const tokenVar of tokenVars) {
            const match = body.match(
                new RegExp(`${tokenVar}\\s*:\\s*([^;]+);`),
            );
            if (match) {
                values[theme] = {...values[theme], [tokenVar]: match[1].trim()};
            }
        }
    }

    for (const theme of Object.keys(themeSelectors)) {
        for (const tokenVar of tokenVars) {
            if (!values[theme]?.[tokenVar]) {
                throw new Error(
                    `writeWbTokenValues: ${tokenVar} not found for theme "${theme}" in wonder-blocks-tokens CSS`,
                );
            }
        }
    }

    fs.writeFileSync(
        path.join(path.dirname(new URL(import.meta.url).pathname), "wb-token-values.gen.js"),
        "// AUTO-GENERATED by .storybook/main.ts — do not edit\n" +
            `export default ${JSON.stringify(values, null, 4)};\n`,
    );
}

writeWbTokenValues();

const config: StorybookConfig = {
    stories: [
        "../__docs__/**/*.@(mdx|stories.@(ts|tsx))",
        "../__docs__/**/*.mdx",
    ],
    addons: [
        "@storybook/addon-a11y",
        {
            name: "@storybook/addon-docs",
            options: {
                mdxPluginOptions: {
                    mdxCompileOptions: {
                        remarkPlugins: [remarkGfm],
                    },
                },
            },
        },
        "storybook-addon-tag-badges",
        {
            name: "@storybook/addon-mcp",
            options: {
                toolsets: {
                    dev: true,
                    docs: true,
                },
            },
        },
    ],
    features: {
        experimentalComponentsManifest: true,
    },
    staticDirs: ["../static"],
    core: {
        disableTelemetry: true,
    },
    framework: "@storybook/react-vite",
    async viteFinal(config) {
        // Merge custom configuration into the default config
        const {mergeConfig} = await import("vite");

        return mergeConfig(config, {
            // Prevent Vite from inlining phosphor-icons
            build: {
                assetsInlineLimit: 0,
            },
        });
    },
    typescript: {
        reactDocgen: "react-docgen-typescript",
        reactDocgenTypescriptOptions: {
            // Ignore props that have the @ignore tag in the docs
            propFilter: (prop) => prop.tags?.ignore === undefined,
        },
    },
};

export default config;
